import type { TileState } from "../types";

const GUESS_LIST = [
  "about", "above", "abuse", "actor", "acute", "admit", "adopt", "adult", "agent", "agree",
  "alarm", "album", "alert", "alien", "align", "alive", "allow", "alone", "along", "alter",
  "among", "angel", "anger", "angle", "angry", "anime", "ankle", "annex", "apart", "apple",
  "apply", "arena", "argue", "arise", "armor", "array", "aside", "asset", "atlas", "attic",
  "audio", "audit", "avoid", "awake", "award", "aware", "awful", "bacon", "badge", "badly",
  "basic", "basis", "batch", "beach", "beard", "beast", "begin", "being", "below", "bench",
  "berry", "birth", "bitch", "black", "blade", "blame", "blank", "blast", "blaze", "bleed",
  "blend", "bless", "blind", "block", "blood", "bloom", "board", "boost", "booth", "bound",
  "brain", "brand", "brave", "bread", "break", "breed", "brick", "brief", "bring", "broad",
  "brook", "brown", "brush", "build", "bunch", "burst", "buyer", "cabin", "candy", "cargo",
  "carry", "catch", "cause", "chain", "chair", "chalk", "chaos", "charm", "chart", "chase",
  "cheap", "check", "cheek", "chess", "chest", "chief", "child", "chill", "china", "chord",
  "chose", "chunk", "civic", "civil", "claim", "clash", "class", "clean", "clear", "climb",
  "cling", "clock", "clone", "close", "cloud", "coach", "coast", "color", "comet", "coral",
  "could", "count", "court", "cover", "crack", "craft", "crane", "crash", "crawl", "crazy",
  "cream", "crest", "crime", "crisp", "cross", "crowd", "crown", "cruel", "crush", "curve",
  "cycle", "dance", "death", "debug", "decay", "delay", "delta", "dense", "depot", "depth",
  "derby", "diary", "diner", "dirty", "disco", "ditch", "dizzy", "dodge", "doing", "donor",
  "doubt", "dough", "draft", "drain", "drama", "drank", "drape", "dream", "dress", "dried",
  "drift", "drill", "drink", "drive", "drone", "drown", "ducks", "dying", "eager", "early",
  "earth", "eighth", "elect", "elite", "email", "ember", "empty", "enemy", "enjoy", "enter",
  "entry", "equal", "error", "essay", "event", "every", "exact", "exile", "exist", "extra",
  "fable", "faith", "false", "fancy", "fatal", "fault", "feast", "fence", "ferry", "fetch",
  "fever", "fiber", "field", "fifth", "fifty", "fight", "final", "first", "flame", "flash",
  "fleet", "flesh", "float", "flood", "floor", "flour", "fluid", "flush", "flute", "focus",
  "force", "forge", "forth", "forum", "found", "frame", "frank", "fraud", "fresh", "front",
  "frost", "froze", "fruit", "fully", "funny", "ghost", "giant", "given", "glad", "globe",
  "gloom", "glory", "going", "grace", "grade", "grain", "grand", "grant", "graph", "grasp",
  "grass", "grave", "great", "green", "greet", "grief", "grill", "grind", "groan", "gross",
  "group", "grove", "grown", "guard", "guess", "guest", "guide", "guild", "guilt", "happy",
  "harsh", "haste", "haunt", "haven", "heart", "heavy", "hence", "herbs", "honor", "horse",
  "hotel", "house", "human", "humor", "hurry", "ideal", "image", "imply", "index", "inner",
  "input", "irony", "ivory", "joint", "joker", "judge", "juice", "karma", "kayak", "knack",
  "kneel", "knife", "knock", "known", "label", "large", "laser", "later", "laugh", "layer",
  "learn", "lease", "least", "leave", "legal", "lemon", "level", "light", "limit", "linen",
  "liver", "lobby", "local", "login", "logic", "loose", "lover", "lower", "loyal", "lucky",
  "lunch", "lying", "magic", "major", "maker", "manor", "march", "match", "maybe", "mayor",
  "media", "mercy", "merit", "metal", "meter", "micro", "might", "mimic", "mince", "minor",
  "minus", "mixer", "model", "money", "month", "moral", "mount", "mouse", "mouth", "movie",
  "muddy", "multi", "music", "naive", "nerve", "never", "night", "noble", "noise", "north",
  "noted", "novel", "nurse", "nylon", "occur", "ocean", "offer", "often", "olive", "onset",
  "opera", "orbit", "order", "other", "outer", "oxide", "ozone", "panda", "panel", "panic",
  "paper", "party", "pasta", "patch", "pause", "peace", "pearl", "penny", "perch", "phase",
  "phone", "photo", "piano", "piece", "pilot", "pinch", "pitch", "pixel", "pizza", "place",
  "plain", "plane", "plant", "plate", "plaza", "plead", "pluck", "plumb", "point", "polar",
  "pound", "power", "press", "price", "pride", "prime", "print", "prior", "prize", "probe",
  "proof", "proud", "prove", "psalm", "pulse", "punch", "pupil", "purse", "pushy", "pussy",
  "queen", "query", "quest", "queue", "quick", "quiet", "quota", "quote", "radar", "radio",
  "ranch", "range", "rapid", "ratio", "reach", "react", "ready", "realm", "rebel", "reddy",
  "refer", "reign", "relax", "reply", "rider", "rifle", "right", "rigid", "risky", "rival",
  "river", "roast", "robot", "rocky", "rouge", "rough", "round", "route", "royal", "ruler",
  "rural", "salad", "sauce", "scale", "scare", "scene", "scent", "scope", "score", "scout",
  "scrap", "seize", "sense", "serve", "setup", "seven", "shade", "shaft", "shake", "shame",
  "shape", "share", "shark", "sharp", "shelf", "shell", "shift", "shine", "shirt", "shock",
  "shoot", "shore", "short", "shout", "siege", "sight", "sigma", "since", "sixth", "sixty",
  "skill", "skull", "slate", "slave", "sleep", "slice", "slide", "slope", "small", "smart",
  "smell", "smile", "smoke", "snake", "solar", "solid", "solve", "sorry", "sound", "south",
  "space", "spare", "speak", "speed", "spend", "spill", "spine", "spite", "split", "spoke",
  "sport", "spray", "squad", "stack", "staff", "stage", "stain", "stake", "stale", "stall",
  "stamp", "stand", "stark", "start", "state", "stays", "steak", "steal", "steam", "steel",
  "steep", "steer", "stern", "stick", "stiff", "still", "stock", "stone", "stood", "store",
  "storm", "story", "strip", "stuck", "study", "stuff", "style", "sugar", "suite", "sunny",
  "super", "surge", "swamp", "swear", "sweep", "sweet", "swept", "swift", "swing", "sword",
  "syrup", "table", "taste", "teach", "tempo", "thank", "theft", "theme", "thick", "thief",
  "thing", "think", "third", "those", "three", "threw", "throw", "thumb", "tiger", "tight",
  "timer", "tired", "title", "today", "token", "tooth", "topic", "total", "touch", "tough",
  "towel", "tower", "toxic", "trace", "track", "trade", "trail", "train", "trait", "trash",
  "treat", "trend", "trial", "tribe", "trick", "tried", "troop", "truck", "truly", "trump",
  "trunk", "trust", "truth", "tumor", "tuner", "tweed", "twice", "twist", "ultra", "uncle",
  "under", "union", "unite", "unity", "until", "upper", "upset", "urban", "usage", "usher",
  "usual", "utter", "valid", "valor", "value", "vapor", "vault", "verse", "video", "vigor",
  "vinyl", "viola", "viral", "virus", "visit", "vista", "vital", "vivid", "vocal", "vodka",
  "voice", "voter", "vowel", "watch", "water", "weary", "weave", "wedge", "weigh", "weird",
  "whale", "wheat", "wheel", "where", "which", "while", "white", "whole", "whose", "widow",
  "width", "witch", "woman", "world", "worry", "worse", "worst", "worth", "would", "wound",
  "wrath", "write", "wrote", "yacht", "yield", "young", "youth", "zebra", "zonal", "abide",
  "abled", "abode", "abort", "acorn", "adore", "affix", "after", "agile", "aging", "aisle",
  "alley", "allot", "aloft", "aloud", "amaze", "amber", "ample", "amuse", "aphid", "apron",
  "aroma", "arose", "arrow", "ashes", "atone", "avert", "axial", "axion", "azure", "bagel",
  "balmy", "bamboo", "banal", "baron", "basin", "bathe", "beans", "beats", "began", "beige",
  "belie", "beset", "bilge", "binge", "bingo", "biome", "biped", "blimp", "bliss", "bloat",
  "blunt", "blurt", "blush", "boast", "bonus", "booby", "bored", "botch", "brawl", "brisk",
  "brittle", "broil", "bronc", "bruin", "brunt", "bryan", "buggy", "bulge", "bully", "bumpy",
  "burly", "burnt", "butch", "cabal", "cacti", "cadet", "cameo", "canal", "canny", "canoe",
  "canon", "caper", "capri", "carat", "caret", "caste", "cater", "cavil", "cedar", "chafe",
  "champ", "chant", "cheat", "chewy", "chimp", "chink", "chips", "choir", "chomp", "chums",
  "cited", "clamp", "clang", "clank", "clasp", "cleat", "clench", "click", "cliff", "clink",
  "cloak", "clomp", "cluck", "clump", "clung", "cobra", "cocoa", "codon", "colic", "combo",
  "comfy", "comic", "comma", "conic", "cooky", "coped", "copia", "copse", "cords", "corks",
  "corns", "corps", "couch", "coven", "covet", "cower", "coyly", "cozen", "crabs", "crags",
  "cramp", "crank", "crate", "crave", "creak", "crepe", "crept", "crick", "crimp", "croak",
  "croft", "crone", "crony", "crook", "croon", "croup", "crude", "crumb", "crump", "crust",
  "crypt", "cubed", "cubic", "cuffs", "cuite", "cumin", "curia", "curio", "curly", "curry",
  "curse", "curst", "cynic", "daddy", "dairy", "daily", "dainty", "dally", "dandy", "dared",
  "darts", "dated", "daunt", "dealt", "debar", "debit", "debut", "decaf", "decal", "decor",
  "decoy", "decry", "defer", "deify", "deign", "deist", "deity", "delve", "demon", "demos",
  "demur", "desks", "deter", "devil", "dewar", "dhoti", "diana", "diced", "dicky", "dicta",
  "diets", "digit", "dikes", "dilly", "dimer", "dimly", "dinar", "dined", "dingo", "dingy",
  "dinky", "dinos", "diode", "dippy", "dirge", "ditto", "ditzy", "divan", "dived", "divot",
  "docks", "dodgy", "dogma", "dolly", "domed", "donut", "doped", "dorky", "dotal", "doter",
  "doted", "douse", "doves", "dowdy", "dowel", "downy", "dowry", "dozed", "drabs", "drake",
  "drawn", "dread", "drier", "droid", "droll", "drops", "dross", "drove", "druid", "drums",
  "drunk", "dryer", "dubby", "dubya", "ducts", "dudes", "duets", "duffs", "dukes", "dulls",
  "dully", "dumbo", "dummy", "dumps", "dumpy", "dunce", "dunes", "dunks", "duped", "dusky",
  "dusty", "dutch", "duvet", "dwarf", "dwell", "dwelt", "dyads", "dyers", "dylan", "eagle",
  "eared", "easel", "eaten", "eater", "ebbed", "ebony", "ebook", "eclat", "edema", "edged",
  "edict", "edify", "edits", "educe", "eerie", "egads", "egged", "egret", "eider", "eight",
  "eject", "eland", "elbow", "elder", "elegy", "elfin", "elide", "elope", "elude", "elven",
  "elves", "embed", "emcee", "emend", "emery", "emirs", "emits", "emote", "enact", "ended",
  "endow", "ennui", "enrol", "ensue", "envoy", "eosin", "epics", "epoch", "epoxy", "equip",
  "erase", "erect", "ergot", "erode", "erupt", "ester", "ether", "ethic", "ethos", "ethyl",
  "etude", "euros", "evade", "evens", "evict", "evoke", "exalt", "excel", "exert", "exits",
  "expat", "expel", "extol", "exude", "exult", "eying", "facet", "faddy", "faded", "fagot",
  "fails", "faint", "fairy", "faker", "falls", "famed", "fangs", "fanny", "farce", "fated",
  "fates", "fatty", "fauna", "feats", "fecal", "feign", "feint", "fella", "felon", "femme",
  "femur", "feral", "feted", "fetid", "fetus", "feuds", "fewer", "ficus", "fidge", "fiefs",
  "fiend", "fiery", "filch", "filer", "files", "filet", "fills", "filly", "filmy", "filth",
  "finch", "finer", "fines", "finis", "finks", "finny", "fiord", "fired", "firer", "firth",
  "fishy", "fisty", "fitly", "fiver", "fixed", "fixer", "fizzy", "fjord", "flack", "flags",
  "flail", "flair", "flake", "flaky", "flank", "flaps", "flare", "flask", "fleck", "flick",
  "flied", "flier", "flies", "fling", "flint", "flirt", "flock", "flops", "flora", "floss",
  "flout", "flown", "fluff", "fluke", "flume", "flung", "flunk", "flyer", "foamy", "focal",
  "fogey", "foist", "fold", "folks", "folly", "foray", "forgo", "forks", "forme", "forte",
  "forty", "fossa", "fouls", "fount", "fours", "fowl", "foxes", "foyer", "frail", "freak",
  "freed", "freer", "friar", "fried", "frill", "frisk", "frizz", "frock", "frond", "frump",
  "fryer", "fulcr", "fumed", "fumer", "funds", "fungi", "funic", "funky", "furor", "furry",
  "furze", "fused", "fussy", "fusty", "futon", "fuzzy", "gabby", "gable", "gaily", "gains",
  "gamer", "games", "gamma", "gamut", "gaols", "gaped", "garde", "gaudy", "gauge", "gaunt",
  "gauze", "gavel", "gawks", "gawky", "gayer", "gayly", "gazed", "gazes", "gears", "gecko",
  "geese", "gemma", "genel", "genes", "genet", "genie", "genii", "genre", "gents", "genus",
  "geode", "ghoul", "giddy", "gifts", "gilds", "gills", "gilts", "gimel", "gimme", "gimpy",
  "gipsy", "girds", "girls", "girly", "giros", "girth", "girts", "giver", "gives", "gizmo",
  "glade", "gland", "glans", "glare", "glass", "glaze", "gleam", "glean", "glebe", "glede",
  "gleek", "glees", "glens", "glide", "glint", "glitz", "gloat", "gloss", "glove", "glows",
  "glued", "gluer", "glues", "gluey", "gluon", "glyph", "gnarl", "gnash", "gnats", "gnaws",
  "gnome", "goads", "goals", "goats", "godly", "goers", "gofer", "golds", "golem", "golfs",
  "goner", "goody", "goofy", "gooey", "goons", "gored", "gorge", "gorse", "goths", "gotta",
  "gouge", "gourd", "gouty", "graft", "grail", "grape", "grate", "gravy", "graze", "grebe",
  "greed", "greys", "grime", "grins", "gripe", "grips", "grist", "groin", "groom", "grope",
  "grout", "growl", "gruel", "gruff", "grunt", "guano", "guava", "guile", "guise", "gulag",
  "gulch", "gulfs", "gulls", "gully", "gumbo", "gummy", "gunny", "guppy", "gurus", "gushy",
  "gusto", "gusts", "gusty", "gutsy", "guts", "gypsy", "habit", "hacky", "hades", "hafts",
  "hague", "haiku", "hairy", "hajji", "hakes", "haled", "haler", "hales", "halls", "halma",
  "halos", "halse", "halts", "halve", "hamal", "hames", "hammy", "hamza", "handy", "hangs",
  "haply", "hards", "hardy", "harem", "harks", "harms", "harps", "harpy", "harry", "harts",
  "hasps", "hasty", "hatch", "hated", "hater", "hates", "hauls", "haves", "havoc", "hawks",
  "hayed", "hazel", "hazly", "heads", "heady", "heals", "heaps", "heard", "heath", "heats",
  "heave", "hedge", "heeds", "heels", "hefty", "heirs", "heist", "helix", "hello", "hells",
  "helms", "helps", "hemps", "henna", "herds", "here", "heron", "heros", "hertz", "hewed",
  "hider", "hides", "highs", "hight", "hijab", "hiked", "hiker", "hills", "hilly", "hilts",
  "hinds", "hinge", "hints", "hippo", "hippy", "hired", "hirer", "hires", "hitch", "hived",
  "hives", "hoagy", "hoard", "hoary", "hobby", "hocus", "hogan", "hoist", "hoked", "hokey",
  "hokum", "holds", "holed", "holes", "holey", "holly", "homer", "homes", "homey", "honed",
  "honey", "hooch", "hoods", "hoody", "hoofs", "hooks", "hooky", "hoops", "hoots", "hoped",
  "hopes", "horde", "horns", "horny", "horsy", "hosed", "hosts", "hotly", "hound", "hours",
  "hovel", "hover", "howdy", "howls", "hubby", "huffy", "huger", "hulas", "hulks", "hulls",
  "humid", "humps", "humpy", "hunch", "hunks", "hunts", "hurds", "hurls", "hurts", "husks",
  "husky", "hussy", "hutch", "hydra", "hydro", "hyena", "hying", "hymns", "hyper", "hypha",
  "hyrax", "iambi", "iambs", "ichor", "icier", "icily", "icing", "icons", "ideas", "idiom",
  "idiot", "idled", "idler", "idols", "idyll", "igloo", "iliac", "ilium", "imams", "imbue",
  "impel", "inane", "inapt", "incur", "indie", "inept", "inert", "infix", "ingot", "injun",
  "inked", "inlet", "inset", "inter", "intra", "inure", "iodin", "ionic", "irate", "irons",
  "isles", "islet", "issue", "itchy", "items", "jacks", "jaded", "jaggy", "jails", "james",
  "japan", "jaunt", "jawed", "jazzy", "jeans", "jells", "jelly", "jenny", "jerks", "jerky",
  "jests", "jetty", "jewel", "jibed", "jiffy", "jihad", "jilts", "jimmy", "jinks", "jinni",
  "jinns", "jivey", "jolts", "jotty", "joules", "joust", "jowls", "jowly", "joyed", "jubas",
  "jubes", "judas", "juicy", "julep", "jumbo", "jumps", "jumpy", "junco", "junta", "junto",
  "juror", "kabob", "kafka", "kandy", "kanna", "kapok", "kappa", "kazoo", "kebab", "kebob",
  "keels", "keens", "keeps", "kefir", "kelly", "kelps", "kelpy", "kenya", "ketch", "kexes",
  "keyed", "khaki", "kicks", "kicky", "kiddo", "kiddy", "kills", "kilns", "kilos", "kilts",
  "kinda", "kinds", "kings", "kinks", "kinky", "kiosk", "kiwis", "klick", "klutz", "knave",
  "knead", "kneed", "knell", "knelt", "knits", "knobs", "knoll", "knots", "knout", "knurl",
  "koala", "kohls", "kooky", "koran", "korea", "kraal", "kraft", "kraut", "krebs", "krill",
  "krona", "krone", "kudos", "kumys", "kurta", "kyats", "labia", "labor", "laced", "lacer",
  "laces", "lacey", "lacks", "laded", "laden", "ladle", "lager", "laird", "lairy", "laity",
  "lakes", "lamas", "lambs", "lamed", "lamer", "lames", "lamps", "lance", "lands", "lanes",
  "lanky", "lapel", "lapis", "lapse", "larch", "lards", "lardy", "largo", "larks", "larva",
  "lasso", "lasts", "latch", "latex", "lathe", "laths", "latin", "laude", "lawns", "lawny",
  "laxly", "layup", "lazed", "lazes", "leach", "leads", "leafy", "leaks", "leaky", "leans",
  "leant", "leaps", "leapt", "leash", "ledge", "leech", "leeks", "leers", "leery", "lefts",
  "lefty", "leger", "leggy", "legit", "lemme", "lemur", "lends", "length", "lenis", "lenny",
  "lense", "lento", "leone", "leper", "lepta", "lesbo", "letch", "letup", "leuds", "levee",
  "lever", "levin", "levis", "lewdly", "lewis", "lexis", "liars", "libel", "liber", "libra",
  "libri", "lichi", "licit", "licks", "lieds", "liefs", "lien", "liers", "lieus", "lifes",
  "lifts", "ligne", "liked", "liken", "lilac", "lilts", "limbo", "limbs", "limed", "limes",
  "limns", "limos", "limps", "lined", "liner", "lingo", "links", "lints", "linty", "lions",
  "lipid", "lipos", "lippy", "liras", "lisps", "lists", "litre", "lived", "liven", "livid",
  "livre", "llama", "loads", "loafs", "loamy", "loans", "loath", "lobar", "lobed", "lobes",
  "lochs", "locks", "locos", "locum", "locus", "lodge", "loess", "lofts", "lofty", "logan",
  "loges", "loggy", "loins", "lolls", "lolly", "loner", "longs", "looks", "looms", "loons",
  "loony", "loops", "loopy", "loots", "loped", "loper", "lopes", "loppy", "lords", "lores",
  "loris", "losed", "losel", "loser", "loses", "lossy", "lotus", "lough", "louis", "louls",
  "lound", "louns", "louse", "lousy", "louts", "lovat", "loved", "loves", "lowly", "lubes",
  "lucid", "lucks", "lucre", "lulls", "lulus", "lumen", "lumps", "lumpy", "lunar", "lunge",
  "lungs", "lunks", "lunts", "lupin", "lurch", "lured", "lurer", "lures", "lurid", "lurks",
  "lusts", "lusty", "luted", "lutes", "luxes", "lycra", "lymph", "lynch", "lyric", "macaw",
  "maces", "macho", "macro", "madam", "madly", "mafia", "magma", "magna", "magog", "maids",
  "mails", "maims", "mains", "mairs", "maize", "males", "malls", "malt", "mamas", "mamba",
  "mambo", "mamma", "mammy", "maned", "manes", "mange", "mango", "mangy", "mania", "manic",
  "manly", "manna", "manse", "manta", "maori", "maple", "mares", "maria", "marks", "marry",
  "marsh", "marts", "maser", "mason", "masse", "mated", "mater", "mates", "matin", "matte",
  "mauls", "mauve", "maven", "mavin", "maxim", "mayst", "mazed", "mazer", "mazes", "mazur",
  "mccoy", "meads", "meals", "mealy", "means", "meant", "meany", "meats", "meaty", "mebbe",
  "medal", "medic", "meets", "melba", "melds", "melee", "mells", "melon", "melts", "memo",
  "memos", "menad", "mends", "menus", "meows", "merge", "merry", "meson", "messy", "meted",
  "metre", "metro", "mewed", "mewls", "mezzo", "miaow", "miasm", "miaul", "micas", "mice",
  "micks", "midas", "middy", "midge", "midst", "miens", "miffs", "miggs", "miked", "mikes",
  "milch", "mildew", "miler", "miles", "milks", "milky", "mille", "mills", "milos", "milpa",
  "mimed", "mimer", "mimes", "mimis", "minds", "mined", "miner", "mines", "minim", "minks",
  "mints", "mired", "mires", "mirth", "misdo", "miser", "mists", "misty", "miter", "mites",
  "mitre", "mitts", "mixed", "mixes", "mixup", "moans", "moats", "mocha", "mocks", "modal",
  "modem", "modes", "mogul", "moira", "moist", "molal", "molar", "molds", "moldy", "moles",
  "molls", "molly", "molts", "momma", "mommy", "momus", "monad", "monas", "monde", "monal",
  "mondo", "monks", "monte", "mooch", "moods", "moody", "mooed", "moon", "moons", "moony",
  "moors", "moose", "moots", "moped", "mopes", "moray", "morel", "mores", "morns", "moron",
  "morph", "morse", "morts", "mosey", "mossy", "mosts", "motel", "motes", "motet", "moths",
  "mothy", "motif", "motor", "motto", "mould", "mound", "mourn", "mousy", "moved", "mover",
  "moves", "mowed", "mower", "moxie", "mucho", "mucid", "mucus", "muffs", "mufti", "muggy",
  "muggs", "mujik", "mulch", "mulct", "mules", "muley", "mulla", "mumms", "mummy", "mumps",
  "munch", "munge", "mungs", "muras", "mures", "murex", "murid", "murks", "murky", "murry",
  "musca", "mused", "muser", "muses", "mushy", "musks", "musky", "mussy", "musts", "musty",
  "mutch", "muted", "muter", "mutes", "mutts", "muzzy", "mylar", "mynah", "myoid", "myoma",
  "myope", "myopy", "myrrh", "mysid", "myths", "nadir", "naevi", "nails", "naked", "named",
  "names", "nanny", "naomi", "nappy", "narcs", "nards", "nares", "naric", "narks", "narky",
  "nasal", "nasty", "natal", "natch", "nates", "natty", "naval", "navel", "naves", "nazis",
  "neaps", "nears", "neath", "neats", "necks", "needs", "needy", "neigh", "neons", "nerdy",
  "nerol", "nerts", "nervy", "nests", "newel", "newer", "newly", "newsy", "newts", "nexus",
  "nicer", "niche", "nicks", "niece", "nifty", "nighs", "nihil", "nills", "nines", "ninja",
  "ninth", "nippy", "nisei", "nisse", "niter", "nites", "nitre", "nitro", "nitty", "nixed",
  "nixer", "nixes", "nixon", "noahs", "nobby", "nobel", "nobly", "nodal", "noddy", "nodes",
  "noels", "nohow", "noisy", "nomas", "nomad", "nonce", "nones", "nonet", "nooks", "noons",
  "noose", "nopal", "norms", "nosed", "noses", "nosey", "notal", "notch", "notes", "notum",
  "nouns", "novae", "novas", "noway", "noyes", "nozle", "nubby", "nuder", "nudes", "nudge",
  "nuked", "nukes", "nulls", "numbs", "nunch", "nurds", "nurdy", "nurls", "nutsy", "nutty",
  "nyala", "nymph", "oaken", "oakum", "oared", "oases", "oasis", "oaths", "obese", "obeys",
  "obits", "objct", "oboes", "obols", "ocher", "ochre", "octad", "octal", "octan", "octet",
  "odder", "oddly", "odeon", "odors", "odour", "offal", "offed", "ofter", "ogled", "ogler",
  "ogles", "ogres", "ohmic", "oiled", "oiler", "oinks", "okapi", "okays", "okra", "olden",
  "older", "oldie", "oleic", "oleos", "ombre", "omega", "omens", "omits", "oncet", "onion",
  "oodles", "oomph", "oozed", "oozes", "opals", "opens", "opine", "opium", "opted", "optic",
  "orals", "orate", "orcas", "organ", "oriel", "orris", "osier", "otter", "ought", "ounce",
  "ousts", "outdo", "outgo", "outre", "ovals", "ovary", "ovate", "ovens", "overs", "overt",
  "ovoid", "ovule", "owlet", "owner", "oxbow", "oxeye", "oxlip", "paced", "pacer", "paces",
  "packs", "paddy", "padre", "paean", "pagan", "pages", "pails", "pains", "paint", "pairs",
  "paled", "paler", "pales", "palms", "palmy", "palsy", "pansy", "pants", "papal", "papas",
  "parch", "pared", "pares", "paris", "parka", "parks", "parrs", "parse", "parta", "parts",
  "pasha", "passe", "paste", "pasty", "pated", "paten", "pater", "paths", "patio", "patsy",
  "patty", "pavan", "paved", "paven", "paver", "paves", "pavis", "pawed", "pawer", "pawls",
  "pawns", "payed", "payee", "payer", "peach", "peaks", "peaky", "peals", "pears", "pease",
  "peats", "peaty", "peavy", "pecan", "pecco", "pedal", "pedes", "pedro", "peeks", "peels",
  "peens", "peeps", "peers", "peggy", "peine", "pekoe", "pelts", "penal", "pence", "penes",
  "pengo", "penis", "penna", "penne", "peons", "peony", "pepla", "pepos", "peppy", "percs",
  "perdu", "perdy", "peris", "perks", "perky", "perms", "perps", "perry", "perse", "pervs",
  "pesky", "pesos", "pesto", "pests", "petal", "peter", "petit", "petti", "petto", "petty",
  "pewee", "pewit", "phage", "phial", "phlox", "phony", "phyla", "phyle", "picas", "picks",
  "picky", "picot", "piers", "pieta", "piety", "piggy", "pigmy", "piing", "piked", "piker",
  "pikes", "pilaf", "pilau", "pilaw", "piled", "pilei", "piles", "pills", "pilus", "pimps",
  "pined", "pines", "piney", "pinko", "pinks", "pinky", "pints", "pinup", "pions", "pious",
  "piped", "piper", "pipes", "pipit", "pique", "pithy", "piton", "pivot", "pixes", "plage",
  "plaid", "plait", "plank", "plash", "plats", "platt", "playa", "plays", "pleas", "pleat",
  "plebe", "plebs", "plena", "pleon", "plex", "plied", "plies", "plink", "plots", "plume",
  "plump", "plums", "plumy", "plunk", "plush", "pluto", "poach", "pocks", "pocky", "podgy",
  "podia", "poems", "poesy", "poets", "poise", "poked", "poker", "pokes", "pokey", "poled",
  "poler", "poles", "polio", "polis", "polka", "polls", "polyp", "pomps", "ponce", "ponds",
  "pones", "pooch", "poohs", "pools", "poops", "popes", "poppa", "poppy", "popsy", "porch",
  "pored", "pores", "porky", "porno", "ports", "posed", "poser", "poses", "poset", "posit",
  "posse", "potty", "pouch", "pours", "pouts", "pram", "prank", "prate", "prawn", "preen",
  "preys", "pried", "prier", "pries", "prigs", "primp", "prism", "privy", "prods", "proem",
  "profit", "prole", "proms", "prone", "prong", "props", "prose", "prosy", "prowl", "prows",
  "proxy", "prude", "prune", "pshaw", "psoas", "pucka", "pucks", "puffs", "puffy", "puked",
  "pukes", "puled", "pules", "pulls", "pulps", "pulpy", "pumas", "pumps", "punce", "pungs",
  "punks", "punky", "punts", "pupae", "pupal", "puppy", "puree", "purer", "purge", "purls",
  "purrs", "pursy", "putts", "putty", "pygmy", "pylon", "pyres", "pyrex", "pyxed", "pyxes",
  "qophs", "quack", "quaff", "quail", "quake", "qualm", "quark", "quart", "quash", "quasi",
  "quays", "queer", "quell", "quiff", "quill", "quilt", "quint", "quips", "quipu", "quire",
  "quirk", "quirt", "quite", "quits", "quoin", "quoit", "quoth", "qwert", "rabat", "rabbi",
  "rabid", "raced", "racer", "races", "racks", "radii", "radix", "radon", "rafts", "ragas",
  "raged", "rages", "raids", "rails", "rains", "rainy", "raise", "rajah", "raked", "raker",
  "rakes", "rally", "ramps", "rangy", "ranks", "rants", "rarer", "rasps", "raspy", "ratty",
  "raved", "ravel", "raven", "raves", "rawer", "rayed", "rayon", "razed", "razes", "razor",
  "reads", "reals", "reams", "reaps", "rearm", "rears", "rebus", "rebut", "recap", "recon",
  "recut", "redid", "redux", "reedy", "reels", "reeve", "regal", "rehab", "reins", "relay",
  "relic", "remap", "remit", "remix", "renal", "rends", "renew", "rents", "repay", "repel",
  "reran", "rerun", "resin", "rests", "retch", "retie", "retro", "retry", "reuse", "revel",
  "revue", "rheum", "rhino", "rhyme", "riced", "ricer", "rices", "rides", "ridge", "rifts",
  "rigor", "rimed", "rimes", "rinds", "rindy", "rings", "rinks", "rinse", "riots", "riped",
  "ripen", "riper", "ripes", "risen", "riser", "rises", "risks", "rites", "ritzy", "riven",
  "rivet", "roach", "roads", "roams", "roans", "roars", "robed", "robes", "robin", "rocks",
  "rodeo", "rogan", "rogue", "roils", "roily", "roles", "rolls", "roman", "romeo", "romps",
  "roods", "roofs", "rooks", "rooky", "rooms", "roomy", "roost", "roots", "rooty", "roped",
  "roper", "ropes", "roses", "rosin", "rotas", "rotor", "rouse", "routh", "roved", "rover",
  "roves", "rowan", "rowdy", "rowed", "rowel", "rower", "rubby", "rubel", "rubes", "ruble",
  "ruddy", "ruder", "rufus", "rugby", "ruing", "ruins", "ruled", "rules", "rumba", "rumen",
  "rummy", "rumor", "rumps", "runes", "rungs", "runic", "runny", "runts", "runty", "rupee",
  "ruses", "rushy", "rusks", "rusts", "rusty", "rutch", "ruths", "rutin", "rutty", "saber",
  "sable", "sabot", "sabra", "sabre", "sacks", "sacra", "sadly", "sadhu", "safes", "saggy",
  "sagas", "sages", "sahib", "sails", "saint", "saith", "sakes", "sales", "sally", "salon",
  "salsa", "salts", "salty", "salve", "salvo", "samba", "sands", "sandy", "saner", "sangs",
  "sans", "santo", "sapid", "sappy", "saran", "sarge", "sassy", "satay", "sated", "sates",
  "satin", "satyr", "saucy", "sauna", "saute", "saved", "saver", "saves", "savor", "savvy",
  "sawed", "scabs", "scads", "scald", "scalp", "scaly", "scamp", "scams", "scans", "scant",
  "scape", "scarf", "scarp", "scars", "scary", "scats", "schmo", "schwa", "scion", "scoff",
  "scold", "scone", "scoop", "scoot", "scorn", "scour", "scows", "scrag", "scram", "screw",
  "scrim", "scrip", "scrub", "scuba", "scuff", "scull", "scums", "scurf", "seals", "seams",
  "seamy", "sears", "seats", "sebum", "sects", "sedan", "sedge", "sedgy", "seeds", "seedy",
  "seeks", "seems", "seeps", "seers", "seine", "sepal", "sepia", "sepic", "septa", "serac",
  "serai", "seral", "sered", "serer", "serfs", "serge", "serif", "serum", "servo", "sever",
  "sewed", "sewer", "sexed", "sexy", "shack", "shads", "shady", "shags", "shako", "shaky",
  "shale", "shall", "shalt", "shank", "shard", "shave", "shawl", "sheaf", "shear", "sheen",
  "sheep", "sheer", "sheet", "sheik", "shewn", "shied", "shier", "shies", "shill", "shims",
  "shins", "shiny", "ships", "shire", "shirk", "shish", "shiva", "shoal", "shoed", "shoes",
  "shoji", "shone", "shook", "shorn", "shote", "shots", "shove", "shown", "showy", "shred",
  "shrew", "shrub", "shrug", "shuck", "shunt", "shush", "shyly", "sibyl", "sided", "sides",
  "sidle", "sieve", "signs", "silks", "silky", "sills", "silly", "silos", "silts", "silty",
  "sines", "sinew", "singe", "sings", "sinhs", "sinks", "sinus", "sired", "siren", "sires",
  "sirup", "sises", "sissy", "sitar", "sited", "sites", "size", "sized", "sizer", "sizes",
  "skate", "skeet", "skids", "skied", "skier", "skies", "skiff", "skimp", "skims", "skins",
  "skint", "skips", "skirt", "skits", "skulk", "skunk", "skyed", "slabs", "slack", "slags",
  "slain", "slake", "slams", "slang", "slant", "slash", "slats", "sleek", "sleet", "slept",
  "slick", "slime", "slimy", "sling", "slink", "slips", "slits", "slobs", "sloop", "slops",
  "slosh", "sloth", "slots", "slows", "slugs", "slump", "slums", "slung", "slunk", "slurp",
  "slurs", "slush", "slyly", "smack", "smash", "smear", "smelt", "smirk", "smite", "smith",
  "smock", "smoky", "smote", "snack", "snafu", "snags", "snail", "snaky", "snaps", "snare",
  "snark", "snarl", "sneak", "sneer", "snide", "sniff", "snipe", "snips", "snobs", "snore",
  "snort", "snots", "snout", "snows", "snowy", "snubs", "snuff", "soaps", "soapy", "soars",
  "sober", "socks", "sodas", "sofas", "softa", "softs", "soggy", "soils", "soled", "soles",
  "solos", "somas", "sonar", "songs", "sonic", "sonny", "sooth", "soots", "sooty", "sophs",
  "soppy", "sore", "sorta", "sorts", "sough", "souls", "soups", "soupy", "sours", "sower",
  "spade", "spank", "spans", "spark", "spasm", "spate", "spawn", "spays", "spear", "speck",
  "spell", "spent", "sperm", "spice", "spicy", "spied", "spiel", "spies", "spike", "spiky",
  "spilt", "spins", "spiny", "spire", "spits", "spitz", "spivs", "splat", "splay", "spoil",
  "spoof", "spook", "spool", "spoon", "spore", "spots", "spout", "spree", "sprig", "spunk",
  "spurn", "spurs", "spurt", "squab", "squat", "squaw", "squid", "stabs", "stags", "stagy",
  "staid", "stair", "stalk", "stank", "staph", "stare", "stars", "stash", "stave", "stead",
  "steed", "stein", "stems", "steps", "stews", "stile", "stilt", "sting", "stink", "stint",
  "stoic", "stoke", "stole", "stomp", "stool", "stoop", "stork", "stout", "stove", "strap",
  "straw", "stray", "strop", "stump", "stung", "stunk", "stunt", "suave", "sucks", "suing",
  "suits", "sulks", "sulky", "sully", "sumac", "summa", "sumos", "sunup", "supra", "surah",
  "sural", "surds", "sure", "surfs", "surfy", "surgy", "surly", "surra", "sushi", "swabs",
  "swags", "swain", "swamy", "swang", "swank", "swans", "swap", "sward", "swarm", "swath",
  "swats", "sways", "sweat", "swede", "swell", "swigs", "swill", "swims", "swine", "swipe",
  "swirl", "swish", "swoop", "swore", "sworn", "swung", "sylph", "synch", "syncs", "synod",
  "tabby", "taboo", "tabor", "tache", "tacit", "tacks", "tacky", "tacos", "taffy", "tails",
  "taint", "taken", "taker", "takes", "talcs", "tales", "talks", "talky", "tally", "talon",
  "talus", "tamed", "tamer", "tames", "tamps", "tangy", "tanks", "tansy", "taper", "tapes",
  "tapir", "tapis", "tappa", "taros", "tarot", "tarry", "tarsi", "tarts", "tarty", "tasks",
  "tasty", "tater", "tatty", "taunt", "taupe", "tawny", "taxed", "taxer", "taxes", "taxis",
  "teaks", "teams", "tears", "teary", "tease", "teats", "teddy", "teems", "teens", "teeny",
  "teeth", "telex", "tells", "temps", "tempt", "tends", "tenet", "tenor", "tense", "tenth",
  "tents", "tepid", "terms", "terne", "terns", "terry", "terse", "tests", "testy", "tetra",
  "texas", "texts", "thane", "thaws", "their", "there", "therm", "these", "theta", "thigh",
  "thill", "thins", "thong", "thorn", "throb", "throe", "thrum", "thuds", "thugs", "thump",
  "thyme", "tiara", "tibia", "tidal", "tides", "tiers", "tilde", "tiled", "tiler", "tiles",
  "tills", "tilts", "timed", "times", "timid", "tinct", "tinge", "tinny", "tints", "tipis",
  "tires", "tithe", "titty", "toads", "toady", "toast", "toddy", "toffs", "toffy", "togas",
  "toils", "toits", "toked", "toker", "tokes", "tolls", "tombs", "tomes", "tonal", "tongs",
  "tonic", "tonne", "tools", "topaz", "toque", "torch", "torsi", "torso", "torte", "torus",
  "toted", "totem", "toter", "totes", "tours", "touse", "touts", "toward", "towns", "toxin",
  "tramp", "trams", "traps", "trawl", "tread", "treed", "trees", "treks", "tress", "triad",
  "trier", "trill", "trims", "tripe", "trips", "trite", "trods", "troll", "trope", "trots",
  "trout", "trove", "truce", "truer", "truss", "tryst", "tubal", "tubby", "tubed", "tuber",
  "tubes", "tucks", "tufts", "tufty", "tulip", "tulle", "tuned", "tunes", "tunny", "tupik",
  "turbo", "turds", "turfs", "turfy", "turks", "turn", "turnt", "turps", "turse", "tusks",
  "tutor", "tutus", "tuxes", "tweet", "twerk", "twerp", "twigs", "twill", "twine", "twink",
  "twins", "twirl", "twixt", "tying", "tykes", "typed", "types", "typo", "typos", "tyres",
  "udder", "ukase", "ulcer", "ulnar", "umbel", "umber", "umbra", "unais", "unapt", "unarm",
  "unbar", "unbid", "unbox", "uncap", "uncia", "uncos", "uncut", "undid", "undue", "unfed",
  "unfit", "unfix", "unlit", "unpen", "unpin", "unrig", "unset", "untie", "unwed", "unzip",
  "urged", "urger", "urges", "urine", "users", "using", "usurp", "usury", "uteri", "uvula",
  "vacua", "vagal", "vague", "vagus", "vails", "vairs", "vaker", "vales", "valet", "valve",
  "vamps", "vaned", "vanes", "vangs", "vapid", "varia", "vario", "varus", "vases", "vasts",
  "vaunt", "veals", "veeps", "veers", "vegan", "veils", "veins", "veiny", "velar", "velds",
  "veldt", "venal", "vends", "venge", "venom", "vents", "venue", "verbs", "verge", "verso",
  "verst", "verts", "verve", "vests", "vetch", "vexed", "vexer", "vexes", "vials", "viand",
  "vibes", "viced", "vices", "viers", "views", "viler", "villa", "villi", "vinal", "vines",
  "vinic", "viols", "viper", "vires", "virge", "virgo", "visas", "vised", "vises", "visor",
  "vitta", "vixen", "vogue", "voici", "voids", "voila", "voile", "volar", "voled", "volts",
  "volva", "vomer", "vomit", "votes", "vouch", "vowed", "vower", "voxel", "vroom", "vuggs",
  "vuggy", "vulva", "vying", "wacko", "wacky", "wader", "wades", "wadis", "wafer", "wafts",
  "waged", "wager", "wages", "wagon", "waifs", "wails", "wains", "wairs", "waist", "waits",
  "waive", "waked", "waken", "waker", "wakes", "walks", "walls", "waltz", "wands", "waned",
  "wanes", "wanky", "wanly", "wants", "wards", "wares", "warms", "warns", "warps", "warts",
  "warty", "washy", "wasps", "waspy", "waste", "watus", "wauls", "waved", "waver", "waves",
  "waxed", "waxer", "waxes", "weald", "weals", "weans", "wears", "weber", "wedgy", "weeds",
  "weedy", "weeks", "weeps", "weepy", "welch", "welds", "wells", "welsh", "welts", "wench",
  "wends", "wetly", "whack", "whams", "wharf", "whats", "wheal", "whelk", "whelm", "whelp",
  "whiff", "whims", "whine", "whins", "whiny", "whips", "whirl", "whirr", "whirs", "whish",
  "whisk", "whist", "whits", "whizz", "whomp", "whoop", "whops", "whore", "whorl", "whump",
  "wicks", "wield", "wifed", "wifes", "wight", "wilco", "wilds", "wiled", "wiles", "wilts",
  "wimps", "wimpy", "wince", "winch", "winds", "windy", "wined", "wings", "winks", "winos",
  "wiped", "wiper", "wipes", "wired", "wirer", "wires", "wised", "wiser", "wises", "wisps",
  "wispy", "withe", "withs", "witty", "wived", "wiver", "wives", "wizes", "woken", "wolds",
  "wombs", "women", "wonks", "wonky", "woods", "woody", "wooed", "wooer", "woofs", "wools",
  "wooly", "woops", "woosh", "words", "wordy", "wore", "works", "worms", "wormy", "worts",
  "woven", "wowed", "wrack", "wrang", "wrapt", "wreak", "wreck", "wrens", "wrest", "wrick",
  "wring", "wrist", "writs", "wrong", "wroth", "wrung", "wryly", "wurst", "wussy", "xebec",
  "xenia", "xenon", "xeric", "xerox", "xerus", "xylan", "xylem", "xylol", "xylos", "xylyl",
  "xysti", "xysts", "yacks", "yaffs", "yahoo", "yales", "yamen", "yanks", "yappy", "yards",
  "yarns", "yawed", "yawns", "yawps", "yeahs", "yearn", "years", "yeast", "yecch", "yechs",
  "yechy", "yells", "yelps", "yenta", "yepes", "yerba", "yergs", "yeses", "yests", "yetis",
  "yetts", "yeuks", "yeuky", "yikes", "yills", "yince", "yipes", "yirds", "yirrs", "yodel",
  "yodle", "yogas", "yogee", "yogin", "yogis", "yoked", "yokel", "yokes", "yolks", "yolky",
  "yomps", "yonic", "yonis", "yores", "yowes", "yowie", "yowls", "yuans", "yucas", "yucca",
  "yucch", "yucks", "yucky", "yugas", "yukky", "yulan", "yules", "yummy", "yumps", "yupon",
  "yuppy", "yurta", "yurts", "zaire", "zamia", "zanza", "zappy", "zarfs", "zaxes", "zayin",
  "zeals", "zebus", "zeins", "zerks", "zeros", "zests", "zesty", "zetas", "zibet", "zilch",
  "zincs", "zincy", "zineb", "zines", "zings", "zingy", "zinky", "zippy", "zircs", "zitis",
  "zizit", "zloty", "zoned", "zones", "zonks", "zooey", "zooid", "zooks", "zooms", "zoris",
  "zouks", "zowie", "zymes",
];

const EASY_WORDS = [
  "about", "above", "after", "again", "alive", "allow", "alone", "along", "among", "angel",
  "angry", "apple", "basic", "beach", "begin", "being", "below", "black", "blank", "blind",
  "block", "blood", "bloom", "board", "brave", "bread", "break", "brick", "brief", "bring",
  "brown", "brush", "build", "bunch", "carry", "catch", "chair", "chalk", "chase", "cheap",
  "check", "cheer", "chess", "chief", "child", "class", "clean", "clear", "clock", "close",
  "cloud", "coast", "color", "could", "count", "cover", "crack", "craft", "cream", "cross",
  "crowd", "crown", "dance", "dream", "dress", "drink", "drive", "early", "earth", "eight",
  "enjoy", "enter", "every", "faith", "field", "fight", "final", "first", "flame", "flash",
  "floor", "focus", "force", "forge", "fresh", "front", "fruit", "ghost", "giant", "glass",
  "globe", "grace", "grade", "grain", "grand", "grant", "grass", "great", "green", "group",
  "guard", "guess", "guide", "happy", "heart", "heavy", "horse", "house", "human", "humor",
  "ideal", "image", "joint", "judge", "juice", "large", "later", "laugh", "learn", "least",
  "leave", "level", "light", "limit", "lunch", "magic", "major", "match", "maybe", "media",
  "metal", "might", "model", "money", "month", "moral", "mount", "mouse", "mouth", "movie",
  "music", "never", "night", "noble", "noise", "north", "ocean", "offer", "often", "order",
  "other", "paper", "party", "peace", "phase", "phone", "photo", "piece", "pilot", "pitch",
  "pizza", "place", "plain", "plane", "plant", "plate", "point", "power", "press", "price",
  "pride", "prime", "print", "prior", "prize", "proof", "proud", "prove", "pulse", "punch",
  "queen", "quick", "quiet", "quote", "radio", "range", "rapid", "reach", "react", "ready",
  "right", "river", "rough", "round", "route", "scale", "scene", "scope", "score", "sense",
  "serve", "seven", "shade", "shake", "shape", "share", "sharp", "shelf", "shell", "shift",
  "shine", "shock", "shoot", "shore", "short", "shout", "sight", "since", "sleep", "slice",
  "slide", "slope", "small", "smart", "smell", "smile", "smoke", "snake", "solar", "solid",
  "solve", "sorry", "sound", "south", "space", "spare", "speak", "speed", "spend", "split",
  "sport", "spray", "squad", "stack", "staff", "stage", "stain", "stake", "stand", "start",
  "state", "steak", "steal", "steam", "steel", "steep", "steer", "stick", "still", "stock",
  "stone", "stood", "store", "storm", "story", "strip", "stuck", "study", "stuff", "style",
  "sugar", "sunny", "super", "table", "taste", "teach", "thank", "theme", "thick", "thing",
  "think", "third", "those", "three", "throw", "thumb", "tiger", "tight", "timer", "title",
  "today", "touch", "tough", "tower", "trace", "track", "trade", "trail", "train", "treat",
  "trial", "tribe", "trick", "truck", "truly", "trust", "truth", "twice", "twist", "uncle",
  "under", "union", "unite", "unity", "upper", "upset", "value", "verse", "video", "visit",
  "vital", "vivid", "voice", "watch", "water", "wheel", "where", "which", "while", "white",
  "whole", "world", "worth", "write", "yield", "young", "youth",
];

const HARD_WORDS = GUESS_LIST.filter((w) =>
  ["j", "q", "x", "z", "v", "k", "w"].some((rare) => w.includes(rare))
).filter((w) => !EASY_WORDS.includes(w));

const STANDARD_WORDS = GUESS_LIST.filter(
  (w) => !EASY_WORDS.includes(w) && !HARD_WORDS.includes(w)
);

export function isValidWord(word: string): boolean {
  return word.length === 5 && GUESS_LIST.includes(word.toLowerCase());
}

export function getRandomWord(): string {
  return GUESS_LIST[Math.floor(Math.random() * GUESS_LIST.length)];
}

export function getWordForMode(gameMode: string, winsThisSession?: number): string {
  if (gameMode === "HIGH_ROLLER") {
    return HARD_WORDS[Math.floor(Math.random() * HARD_WORDS.length)];
  }
  if (gameMode === "INFINITE") {
    const streak = winsThisSession ?? 0;
    if (streak >= 7) return HARD_WORDS[Math.floor(Math.random() * HARD_WORDS.length)];
    if (streak >= 4) return STANDARD_WORDS[Math.floor(Math.random() * STANDARD_WORDS.length)];
    return EASY_WORDS[Math.floor(Math.random() * EASY_WORDS.length)];
  }
  return STANDARD_WORDS[Math.floor(Math.random() * STANDARD_WORDS.length)];
}

export function getDailyWord(): string {
  const today = new Date();
  const seed = today.getFullYear() * 10000 + (today.getMonth() + 1) * 100 + today.getDate();
  return GUESS_LIST[seed % GUESS_LIST.length];
}

export function evaluateGuess(guess: string, target: string): TileState[] {
  const result: TileState[] = Array(5).fill("absent");
  const targetChars = target.toLowerCase().split("");
  const guessChars = guess.toLowerCase().split("");

  for (let i = 0; i < 5; i++) {
    if (guessChars[i] === targetChars[i]) {
      result[i] = "correct";
      targetChars[i] = "*";
      guessChars[i] = "*";
    }
  }

  for (let i = 0; i < 5; i++) {
    if (guessChars[i] === "*") continue;
    const targetIdx = targetChars.indexOf(guessChars[i]);
    if (targetIdx !== -1) {
      result[i] = "present";
      targetChars[targetIdx] = "*";
    }
  }

  return result;
}
